// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEfLcy0qeshgVJ8Oje8rE8ovAGif7ZVMA',
    appId: '1:318873368152:web:dc376f8733d2c0a87a3c2d',
    messagingSenderId: '318873368152',
    projectId: 'tyamo-24051',
    authDomain: 'tyamo-24051.firebaseapp.com',
    storageBucket: 'tyamo-24051.appspot.com',
    measurementId: 'G-HY30NR9SFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6yUQoz85m6avA2vN-1BDG0kbnS4Xv2Q0',
    appId: '1:318873368152:android:295d7549bcf710397a3c2d',
    messagingSenderId: '318873368152',
    projectId: 'tyamo-24051',
    storageBucket: 'tyamo-24051.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIkBRlygPmB1HVei2Vqihrp2dRZxCnRMw',
    appId: '1:318873368152:ios:f067bca6468381747a3c2d',
    messagingSenderId: '318873368152',
    projectId: 'tyamo-24051',
    storageBucket: 'tyamo-24051.appspot.com',
    iosBundleId: 'com.example.tyamo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIkBRlygPmB1HVei2Vqihrp2dRZxCnRMw',
    appId: '1:318873368152:ios:116d1208957142d47a3c2d',
    messagingSenderId: '318873368152',
    projectId: 'tyamo-24051',
    storageBucket: 'tyamo-24051.appspot.com',
    iosBundleId: 'com.example.tyamo.RunnerTests',
  );
}
